# Site settings
baseurl: "/tti"
url: "https://msiam.github.io"
title:
email:
description: > # this means to ignore newlines until "baseurl:"

twitter_username:
github_username:

# Build settings
markdown: kramdown
